print("W5HGen 1.0")

projectName = input("Name of your project. This will be appended as 'w5h-projectName.txt' -> ")

projectTitle = input("What should the header of the file be? -> ")
who = input("Who? Names of people relevent to the project -> ")
what = input("What happened? -> ")
when = input("When did the event happen? -> ")
where = input("Where did the event happen? -> ")
why = input("Why did it happen? -> ")
how = input("How did it happen? -> ")

w5hCreate = open("w5h-" + projectName + ".txt", "w")
w5hCreate.write(projectTitle)
w5hCreate.write("\n")
w5hCreate.write("WHO: " + who)
w5hCreate.write("\n")
w5hCreate.write("WHAT: " + what)
w5hCreate.write("\n")
w5hCreate.write("WHEN: " + when)
w5hCreate.write("\n")
w5hCreate.write("WHERE: " + where)
w5hCreate.write("\n")
w5hCreate.write("WHY: " + why)
w5hCreate.write("\n")
w5hCreate.write("HOW: " + how)
w5hCreate.close()

print("Your file is saved. Here's what it looks like:")
w5hRead = open("w5h-" + projectName + ".txt", "r")
print("NOTE: The beginning and end headers are not included in the text file.")
print("-----BEGIN W5H TEXT-----")
print(w5hRead.read())
print("----END W5H TEXT-----")
w5hRead.close()
